export const newsData = [
  {
    source: { id: null, name: "BBC News" },
    author: null,
    title: "The lasting social impact of fish and chips",
    description: "The relationship between early fish and chip shops and wider society is explored in an exhibition.",
    url: "https://www.bbc.com/news/articles/c51134e4wq4o",
    urlToImage: "https://ichef.bbci.co.uk/news/1024/branded_news/fc33/live/1ecb1d10-1876-11ef-aaa5-2b41c801f9c6.jpg",
    publishedAt: "2024-05-25T06:55:34Z",
    content: "Katy Prickett,BBC News, Norfolk\r\nFish and chip shops had a lasting social impact on the port town, said Gaynor Western\r\nThe role played by fish and chips in enabling women to run their own businesses… [+3836 chars]",
  },
  {
    source: { id: null, name: "BBC News" },
    author: null,
    title: "Mystery as doctor finds live goldfish in garden",
    description: "He thinks maybe a bird dropped the fish and it was lucky to be alive.",
    url: "https://www.bbc.com/news/articles/cl448x6ly4jo",
    urlToImage: "https://ichef.bbci.co.uk/news/1024/branded_news/ac7d/live/0ad67080-20e5-11ef-a3ab-e73c00cc3104.jpg",
    publishedAt: "2024-06-02T14:21:04Z",
    content: "Pamela Bilalova &amp; PA Media,BBC North East &amp; Cumbria\r\nDr Ben Beska placed the fish in a freezer drawer until he got a tank\r\nA junior doctor has ended up with a new pet after a goldfish mysteri… [+2499 chars]",
  },
  {
    source: { id: null, name: "ABC 4" },
    author: "Megan Brugger",
    title: "DWR increases fish limit at Utah lakes in ’emergency change’",
    description: 'In what the Utah Division of Wildlife Resources is calling an "emergency change," anglers can now keep up to 16 trout of any species in some Utah waters.',
    url: "https://www.abc4.com/news/local-news/dwr-increases-fish-limit-at-utah-lakes-in-emergency-change/",
    urlToImage: "https://media.zenfs.com/en/ktvx_articles_781/b86c39666381cb52870c0b81055e7a12",
    publishedAt: "2024-05-13T22:05:42Z",
    content: "SALT LAKE CITY (ABC4) In what the Utah Division of Wildlife Resources is calling an emergency change, anglers can now keep up to 16 trout of any species in some Utah waters.\r\nThe change was issued Mo… [+1306 chars]",
  },
  {
    source: { id: null, name: "Yahoo Entertainment" },
    author: null,
    title: "Arkansas angler double snags trophy fish in Greers Ferry Lake",
    description: null,
    url: "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_58f00ef7-92e1-436e-a87f-07a477247d5e",
    urlToImage: null,
    publishedAt: "2024-05-24T18:14:44Z",
    content: "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]",
  },
  {
    source: { id: null, name: "Gizmodo.com" },
    author: "Vinamrata Chaturvedi, Quartz",
    title: "Everything to Know About Bitcoin Pizza Day",
    description: "On May 22, 2010, a man in Florida paid 10,000 Bitcoin for pizza.Read more...",
    url: "https://gizmodo.com/bitcoin-pizza-day-date-origin-history-cryptocurrency-1851487831",
    urlToImage: "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/98aec6479bad523f5c89763f4acf0cf9.jpg",
    publishedAt: "2024-05-20T13:20:00Z",
    content: "On January 3, 2009, Bitcoins creator, Satoshi Nakamoto, mined the first block of the Bitcoin blockchain, known as the Genesis Block, which contained a reward of 50 Bitcoin. The technical foundations … [+1156 chars]",
  },
  {
    source: { id: "time", name: "Time" },
    author: "Alice Park",
    title: "Why Fish Oil Supplements Can Be Dangerous for the Heart",
    description: "Omega-3 fish oil has a checkered record when it comes to heart benefits. Here’s the latest on the supplement.",
    url: "https://time.com/6980756/omega-3-fish-oil-heart-health/",
    urlToImage: "https://api.time.com/wp-content/uploads/2024/05/GettyImages-1430921498.jpg?quality=85&w=1200&h=628&crop=1",
    publishedAt: "2024-05-21T22:30:00Z",
    content: "Most people are familiar with the best things to eat for a healthy heart: vegetables, low-fat dairy, and lean proteins like fish. Some fish like salmon also have the added benefit of being full of om… [+6100 chars]",
  },
  {
    source: { id: "time", name: "Time" },
    author: "JOSEPH B. FREDERICK and KAREN MATTHEWS / AP",
    title: "New York Magnet Fisher Catches Safe Full of $100s Bills, He Says",
    description: "James Kane has used a powerful magnet to fish all manner of junk from New York City waterways.",
    url: "https://time.com/6985675/new-york-magnet-fisher-catches-safe-full-of-100s-bills/",
    urlToImage: "https://api.time.com/wp-content/uploads/2024/06/Cash_0209c1.jpg?quality=85&w=1200&h=628&crop=1",
    publishedAt: "2024-06-05T00:40:54Z",
    content: "New York James Kane has used a powerful magnet to fish all manner of junk from New York City waterways, but he says the stacks of $100 bills he pulled from a safe were something else entirely.\r\nKanes… [+2938 chars]",
  },
  {
    source: { id: null, name: "ABC 4" },
    author: "Derick Fox",
    title: "See this fish at Strawberry Reservoir? Kill and report it, say officials",
    description: "The Utah Division of Wildlife Resources is asking fishers at Strawberry Reservoir to kill and report any walleye fish after they believe the species was...",
    url: "https://www.abc4.com/news/local-news/see-this-fish-at-strawberry-reservoir-kill-and-report-it-say-officials/",
    urlToImage: "https://media.zenfs.com/en/ktvx_articles_781/9c5fe988ddc20f263a3436f0392887d2",
    publishedAt: "2024-05-14T14:47:28Z",
    content: "HEBER CITY, Utah (ABC4) The Utah Division of Wildlife Resources is asking fishers at Strawberry Reservoir to kill and report any walleye fish after they believe the species was illegally introduced t… [+2941 chars]",
  },
  {
    source: { id: null, name: "Yahoo Entertainment" },
    author: "Sydney Borchers",
    title: "Ocean-born fish seen swimming in Kansas River for first time in a decade: 'Fascinating species'",
    description: "An ocean-born fish that's rarely seen in the Kansas River was spotted by a group of biologists who were on the scene conducting sampling operations for an...",
    url: "https://www.yahoo.com/lifestyle/ocean-born-fish-seen-swimming-220619722.html",
    urlToImage: "https://s.yimg.com/ny/api/res/1.2/CFfo27GKYgNXfn2Tl1r.gg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/fox_news_text_979/2361ab2c9c8d82204789b3c54f16a1c8",
    publishedAt: "2024-06-06T22:06:19Z",
    content: "A group of wildlife biologists recently made a rare discovery after finding a fish thousands of miles away from where it was spawned.\r\nThe Aquatic Invasive Species Crew from the Kansas Department of … [+3076 chars]",
  },
  {
    source: { id: null, name: "Yahoo Entertainment" },
    author: null,
    title: "Mary Mahoney’s pleads guilty to selling frozen, foreign fish as fresh Gulf seafood",
    description: null,
    url: "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_c7f336eb-5961-4bc2-b80a-d3f3762906f6",
    urlToImage: null,
    publishedAt: "2024-05-30T18:38:01Z",
    content: "If you click 'Accept all', we and our partners, including 237 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]",
  },
  {
    source: { id: null, name: "Yahoo Entertainment" },
    author: null,
    title: "Mary Mahoney’s customers defend MS restaurant that sold foreign fish as fresh from Gulf",
    description: null,
    url: "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_4b0c9765-e374-429a-b78d-2d420727ee9c",
    urlToImage: null,
    publishedAt: "2024-06-03T17:30:53Z",
    content: "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]",
  },
  {
    source: { id: null, name: "Yahoo Entertainment" },
    author: null,
    title: "Anglers catching this peculiar fish are urged to ‘kill it on sight’",
    description: null,
    url: "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_5fd40750-d466-42ed-bded-84750a202f1f",
    urlToImage: null,
    publishedAt: "2024-06-04T16:20:31Z",
    content: "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]",
  },
  {
    source: { id: null, name: "Yahoo Entertainment" },
    author: null,
    title: "Fish oil supplements may raise risk of stroke, heart issues, study suggests",
    description: null,
    url: "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_7e4356f6-21e3-4eea-ae54-9e02c64adb68",
    urlToImage: null,
    publishedAt: "2024-05-22T11:32:09Z",
    content: "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]",
  },
  {
    source: { id: null, name: "Nautil.us" },
    author: "Amorina Kingdon",
    title: "Sound rules life underwater",
    description: "Amorina Kingdon’s 3 greatest revelations while writing Sing Like Fish.",
    url: "https://nautil.us/how-sound-rules-life-underwater-633318/",
    urlToImage: "https://assets.nautil.us/sites/3/nautilus/Kingdon_HERO.png?auto=compress&fm=png&ixlib=php-3.3.1",
    publishedAt: "2024-06-04T09:58:38Z",
    content: "1Sound travels very differently in water than air.\r\nLike most humans, I assumed that sound didnt work well in water. After all, Jacques Cousteau himself called the ocean the silent world. I thought, … [+5980 chars]",
  },
  {
    source: { id: "business-insider", name: "Business Insider" },
    author: "Polly Thompson",
    title: "Saudi Arabia's Neom is looking to fill 262 job vacancies. The roles show just how futuristic the megacity could be.",
    description: "Recruitment is underway at Saudi Arabia's ambitious smart city, Neom — 262 vacancies have been listed so far.",
    url: "https://www.businessinsider.com/neom-weird-jobs-needed-run-smart-city-2024-5",
    urlToImage: "https://i.insider.com/66325c3910dfcda4096551f9?width=1200&format=jpeg",
    publishedAt: "2024-05-12T15:30:16Z",
    content: 'This image shows the planned design of The Line.NEOM\r\n<ul><li>Saudi Arabia\'s sprawling megacity, Neom, is billed as a chance to live in the "new future."</li><li>Officials want to fill 262 vacancies.… [+5845 chars]',
  },
  {
    source: { id: null, name: "CNET" },
    author: "David Watsky",
    title: "You Won't Believe How Easy Cooking Salmon in the Air Fryer Is - CNET",
    description: "All you need is an air fryer, a filet of salmon and 10 minutes.",
    url: "https://www.cnet.com/home/kitchen-and-household/you-wont-believe-how-easy-cooking-salmon-in-an-air-fryer-is/",
    urlToImage: "https://www.cnet.com/a/img/resize/c3491cdf0de77232f8f01a5854ad1974eede6c54/hub/2024/05/02/b11f766b-44af-4e32-9632-e34c3ffe78c3/screenshot-2024-05-02-at-1-31-36pm.png?auto=webp&fit=crop&height=675&width=1200",
    publishedAt: "2024-05-16T21:46:00Z",
    content: "Every year, I find a few new ways to use the air fryer. It never ceases to amaze me how well and quickly the air fryer cooks food and how simple it is to clean after. For super simple, healthy weekni… [+3040 chars]",
  },
  {
    source: { id: null, name: "CNET" },
    author: "David Watsky",
    title: "The Secret to Cooking Salmon Perfectly in Your Air Fryer - CNET",
    description: "Turn to the air fryer for perfect salmon with almost no mess or fishy smell to manage.",
    url: "https://www.cnet.com/home/kitchen-and-household/the-secret-to-cooking-salmon-perfectly-in-your-air-fryer/",
    urlToImage: "https://www.cnet.com/a/img/resize/942556751a3f21abfbfa68b2a3d58b0ed4b82a8b/hub/2019/08/18/17bf5cec-4a5e-4ed7-8920-cdbd0be7c3b2/teriyaki-salmon-recipe-chowhound.jpg?auto=webp&fit=crop&height=675&width=1200",
    publishedAt: "2024-05-09T21:03:00Z",
    content: "Every year I find new ways to use the air fryer. It's become my go-to for roasted chicken, replacing my slow and dirty dish-heavy oven recipe. I recently learned to make juicy air fryer cheeseburgers… [+2881 chars]",
  },
  {
    source: { id: null, name: "CNET" },
    author: "David Watsky",
    title: "I Tried Cooking Salmon in the Air Fryer and I'm Never Going Back - CNET",
    description: "Air fryer salmon is the best salmon.",
    url: "https://www.cnet.com/home/kitchen-and-household/i-tried-cooking-salmon-in-the-air-fryer-and-im-never-going-back/",
    urlToImage: "https://www.cnet.com/a/img/resize/c3491cdf0de77232f8f01a5854ad1974eede6c54/hub/2024/05/02/b11f766b-44af-4e32-9632-e34c3ffe78c3/screenshot-2024-05-02-at-1-31-36pm.png?auto=webp&fit=crop&height=675&width=1200",
    publishedAt: "2024-05-13T16:15:00Z",
    content: "Every year, I find a few new ways to use the air fryer. It never ceases to amaze me how well and quickly the air fryer cooks food and how simple it is to clean after. For super simple, healthy weekni… [+3042 chars]",
  },
  {
    source: { id: null, name: "CNET" },
    author: "David Watsky",
    title: "Hot Seafood Summer: These Are the 9 Best Fish to Grill This Summer - CNET",
    description: "Some fish fall apart on the grill while others hold form. Here are the best fish to lay on the grates for your summer feast.",
    url: "https://www.cnet.com/health/nutrition/these-are-the-9-best-fish-to-grill/",
    urlToImage: "https://www.cnet.com/a/img/resize/e52decc611dea830e20917cba9e2a63983443ba2/hub/2024/01/09/4ee3175c-1970-4d6b-a3eb-903366685a25/screenshot-2024-01-09-at-8-28-07am.png?auto=webp&fit=crop&height=675&width=1200",
    publishedAt: "2024-05-25T13:00:04Z",
    content: "Looking to have a hot seafood summer you're going to want some fish to grill. We asked a seafood grillin' expert about the best fish to put on the grates for a fish feat in spring or summer. If you p… [+6716 chars]",
  },
  {
    source: { id: null, name: "Biographic.com" },
    author: "Sarah Gilman, bioGraphic",
    title: "The Curious Life of a ‘Grotesque’ Singing Fish",
    description: "Plainfin midshipmen migrate from the deep sea to the intertidal zone to spawn, and that’s when things really get loud",
    url: "https://www.biographic.com/the-curious-life-of-a-singing-fish/",
    urlToImage: "https://static.scientificamerican.com/dam/m/1bd98cf805f46acc/original/2CW5JWN_WEB.jpg?w=1200",
    publishedAt: "2024-05-24T12:00:00Z",
    content: "The world of larval plainfin midshipman fish (Porichthys notatus) may look alien, but it could be as close as the cobbles beneath your feet, if you walk a rocky stretch of shore on much of the North … [+3400 chars]",
  },
  {
    source: { id: null, name: "Gizmodo.com" },
    author: "Maxwell Zeff",
    title: "Orcas Sink 49-Foot Yacht in Mystifying Trend Around the Strait of Gibraltar",
    description:
      "An unknown number of orcas sunk a sailing yacht in Moroccan waters in the Strait of Gibraltar on Sunday, according to Spain’s maritime rescue service. While orcas are typically peaceful, this is the latest in a string of attacks that have hit the region in th…",
    url: "https://gizmodo.com/orcas-sink-49-foot-yacht-in-mystifying-trend-around-the-1851475384",
    urlToImage: "https://i.kinja-img.com/image/upload/c_fill,h_675,pg_1,q_80,w_1200/b4fffe53de7466f53b81f067bf0fec72.jpg",
    publishedAt: "2024-05-14T14:20:00Z",
    content: "An unknown number of orcas sunk a sailing yacht in Moroccan waters in the Strait of Gibraltar on Sunday, according to Spains maritime rescue service. While orcas are typically peaceful, this is the l… [+2820 chars]",
  },
  {
    source: { id: null, name: "NPR" },
    author: "Nathan Rott",
    title: "Box turtles. Coral. These illegally trafficked animals still need a good home",
    description:
      "When authorities find wildlife that are being illegally trafficked, at ports or airports, the animals are often in terrible shape. Sick, starved, distressed. A pilot project in Southern California aims to get seized wildlife immediate care.",
    url: "https://www.npr.org/2024/05/30/g-s1-1736/illegally-trafficked-wildlife-surging-care-for-animals-southern-california",
    urlToImage: "https://npr.brightspotcdn.com/dims3/default/strip/false/crop/3000x1688+0+313/resize/1400/quality/100/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Fb6%2F2b%2Fd90401c3406ba374c36a857dbc98%2Fd9a1094.jpg",
    publishedAt: "2024-06-08T09:00:00Z",
    content: "TORRANCE, Calif. In the back of an office building, in a small room that smells like rotting strawberries, a criminal investigator watches his evidence crawl around on wood chips in five open plastic… [+7233 chars]",
  },
  {
    source: { id: null, name: "Yahoo Entertainment" },
    author: null,
    title: "Rare fish found near Cannon Beach, 1st time in Oregon",
    description: null,
    url: "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_9c566d16-fb66-4ea6-8d19-23ce5533399f",
    urlToImage: null,
    publishedAt: "2024-05-18T22:22:52Z",
    content: "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]",
  },
  {
    source: { id: null, name: "Skinnytaste.com" },
    author: "Gina",
    title: "Fish en Papillote",
    description:
      "Mediterranean baked Fish en Papillote topped with a beans, Castelvetrano olives, artichoke hearts, cherry tomatoes, and fresh herbs. Fish en Papillote I love a healthy one-pot meal, so this Fish en Papillote (Fish in Parchement) isn’t just easy, is so delicio…",
    url: "https://www.skinnytaste.com/fish-en-papillote/",
    urlToImage: "https://www.skinnytaste.com/wp-content/uploads/2024/05/Branzino-Parchment-Packets-7-scaled.jpg",
    publishedAt: "2024-05-08T19:25:25Z",
    content: "This post may contain affiliate links. Read my disclosure policy.\r\nMediterranean baked Fish en Papillote topped with a beans, Castelvetrano olives, artichoke hearts, cherry tomatoes, and fresh herbs.… [+7895 chars]",
  },
  {
    source: { id: null, name: "MacRumors" },
    author: "Juli Clover",
    title: "Apple Watch Double Tap Feature Highlighted in Latest Apple Ad",
    description:
      "Apple today shared a funny new ad that focuses on the Double Tap feature available on the Apple Watch. In the spot, a man catches a giant fish and while he attempts to wrangle it, he is able to use Double Tap to trigger the Apple Watch to take a photo on a co…",
    url: "https://www.macrumors.com/2024/06/07/apple-watch-double-tap/",
    urlToImage: "https://images.macrumors.com/t/ntRvVXN19tlugnIUuTNwoqxKOgQ=/1600x/article-new/2024/06/apple-watch-double-tap.jpeg",
    publishedAt: "2024-06-07T23:18:34Z",
    content: "Apple today shared a funny new ad that focuses on the Double Tap feature available on the Apple Watch. In the spot, a man catches a giant fish and while he attempts to wrangle it, he is able to use D… [+733 chars]",
  },
  {
    source: { id: "business-insider", name: "Business Insider" },
    author: "mfox@businessinsider.com (Matthew Fox)",
    title: "The state of Wisconsin purchased $163 million in bitcoin ETFs in the first quarter",
    description: "The state of Wisconsin Investment Board purchased bitcoin ETFs from BlackRock and Grayscale in the first quarter, according to a 13F filing.",
    url: "https://markets.businessinsider.com/news/currencies/wisconsin-buys-bitcoin-163-million-crypto-etf-state-investment-board-2024-5",
    urlToImage: "https://i.insider.com/6644fd3b14fb5b23cc5cbfca?width=1200&format=jpeg",
    publishedAt: "2024-05-15T19:47:07Z",
    content: "The state of Wisconsin purchased $163 million worth of bitcoin in the first quarter, according to a 13F filing made with the Securities and Exchange Commission. \r\nThe Wisconsin Investment Board manag… [+1287 chars]",
  },
  {
    source: { id: "business-insider", name: "Business Insider" },
    author: "Polly Thompson",
    title: "Billionaire defense entrepreneur Palmer Luckey has a home like a Bond villain's lair — complete with helicopters, a giant fish tank, and an underground missile base filled with video games",
    description: '"I am a little bit of a caricature," Luckey told Bloomberg after showing off his crazy collection of cars, helicopters, and boats.',
    url: "https://www.businessinsider.com/billionaire-defense-tech-founder-palmer-luckey-private-collection-military-vehicles-2024-5",
    urlToImage: "https://i.insider.com/6645e3d09fc063e829b19501?width=1200&format=jpeg",
    publishedAt: "2024-05-19T10:18:01Z",
    content: "Palmer Luckey, founder of Oculus and Anduril Industries.Patrick T. Fallon/Getty Images\r\n<ul><li>Palmer Luckey's startup Anduril is producing futuristic weapons of war. </li><li>But the billionaire fo… [+3417 chars]",
  },
  {
    source: { id: null, name: "Yahoo Entertainment" },
    author: "Associated Press",
    title: "Rare 7-foot fish washed ashore on Oregon's coast garners worldwide attention",
    description: "A massive rare fish thought to only live in temperate waters in the southern hemisphere has washed up on Oregon's northern coast, drawing crowds of curious...",
    url: "https://www.yahoo.com/news/rare-7-foot-fish-washed-191858184.html",
    urlToImage: "https://s.yimg.com/ny/api/res/1.2/pLPBXV_umgN6bi9GpwXotA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/ap.org/79a7d1550427fffb76343de920491f17",
    publishedAt: "2024-06-07T19:18:58Z",
    content: "GEARHART, Ore. (AP) A massive rare fish thought to only live in temperate waters in the southern hemisphere has washed up on Oregon's northern coast, drawing crowds of curious onlookers intrigued by … [+1648 chars]",
  },
  {
    source: { id: null, name: "NPR" },
    author: "Regina G. Barber",
    title: "A silky shark named Genie swam 17,000 miles, a record-breaking migration",
    description:
      "A silky shark named Genie traveled from the Galapagos Islands out to the open ocean and back – over 17,000 miles – over the course of a year and a half. That's an average of 31 miles per day, making Genie's journey the longest recorded migration for a silky s…",
    url: "https://www.npr.org/2024/05/31/1198910124/silky-shark-record-breaking-migration-galapagos",
    urlToImage: "https://media.npr.org/assets/img/2024/05/30/silky-shark-close-up_pelayo-salinas_wide-f99a8c580335d2ce8a67c2bc225faccf5fcfa1ef.jpg?s=1400&c=100&f=jpeg",
    publishedAt: "2024-05-31T07:00:59Z",
    content: "A silky shark named Genie traveled from the Galapagos Islands out to the open ocean and back over 17,000 miles over the course of a year and a half. This is the longest recorded migration for a silky… [+1197 chars]",
  },
  {
    source: { id: "business-insider", name: "Business Insider" },
    author: "Grace Eliza Goodwin",
    title: "Red Lobster superfans desperately want a piece of the bankrupt chain",
    description: "The company in charge of auctioning off items from 52 shuttered Red Lobster locations had hundreds of fans reaching out, its CEO says.",
    url: "https://www.businessinsider.com/red-lobster-superfans-auctions-bankrupt-restaurant-chain-2024-5",
    urlToImage: "https://i.insider.com/664d02df9fc063e829b37656?width=1200&format=jpeg",
    publishedAt: "2024-05-21T20:44:49Z",
    content: "A Red Lobster in Stony Brook, NY was one of the stores to close in May 2024.John Paraskevas/Newsday RM via Getty Images\r\n<ul><li>Red Lobster fans clamored for sentimental items from the iconic chain,… [+3308 chars]",
  },
  {
    source: { id: "time", name: "Time" },
    author: "Philip Lymbery and Leticia Carvalho",
    title: "Penguins Are Key Indicators of the Ocean’s Health",
    description: "The plight of penguins can serve as a guidepost for what needs to happen if we are to preserve life on both land and sea.",
    url: "https://time.com/6986218/penguins-oceans-health-essay/",
    urlToImage: "https://api.time.com/wp-content/uploads/2024/06/penguins-ocean.jpg?quality=85&w=1200&h=628&crop=1",
    publishedAt: "2024-06-07T11:00:00Z",
    content: "In Bettys Bay, South Africa, one of the worlds wildlife celebrities, an African penguin, was busy shaking herself free from the sea. On land, cute and ungainly in equal measure, this princess of the … [+6370 chars]",
  },
  {
    source: { id: null, name: "MacRumors" },
    author: "Joe Rossignol",
    title: "Apple Arcade Adding These New Games in July",
    description:
      "Apple today revealed three new games coming to Apple Arcade on July 3, including town-building strategy game Outlanders 2: Second Nature, side-scrolling action game Punch Kick Duck+, and the calm and relaxing game Zen Koi Pro+. All games available on Apple Ar…",
    url: "https://www.macrumors.com/2024/06/06/apple-arcade-adding-these-new-games-in-july/",
    urlToImage: "https://images.macrumors.com/t/qeSA2lNWJQSsmfCfgW-ayqjG-uo=/1600x/article-new/2020/06/apple-arcade-orange-feature.jpg",
    publishedAt: "2024-06-06T17:12:21Z",
    content: "Apple today revealed three new games coming to Apple Arcade on July 3, including town-building strategy game Outlanders 2: Second Nature, side-scrolling action game Punch Kick Duck+, and the calm and… [+1539 chars]",
  },
  {
    source: { id: null, name: "Yahoo Entertainment" },
    author: null,
    title: "Biologists find rare ocean-born fish species swimming in the Kansas River",
    description: null,
    url: "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_f3af1c7a-2754-4f98-ae5a-7a9df20866e3",
    urlToImage: null,
    publishedAt: "2024-05-27T18:04:13Z",
    content: "If you click 'Accept all', we and our partners, including 237 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]",
  },
  {
    source: { id: null, name: "Science Daily" },
    author: null,
    title: "Fish out of water: How killifish embryos adapted their development",
    description:
      "The annual killifish lives in regions with extreme drought. A research group now reports that the early embryogenesis of killifish diverges from that of other species. Unlike other fish, their body structure is not predetermined from the outset. This could en…",
    url: "https://www.sciencedaily.com/releases/2024/06/240606152359.htm",
    urlToImage: "https://www.sciencedaily.com/images/scidaily-icon.png",
    publishedAt: "2024-06-06T19:23:59Z",
    content: "The annual killifish lives in regions with extreme drought. A research group at the University of Basel now reports in Science that the early embryogenesis of killifish diverges from that of other sp… [+2876 chars]",
  },
  {
    source: { id: null, name: "Eatingwell.com" },
    author: "Victoria Whittington, RDN",
    title: "The 7 Best Canned Foods You Should Be Eating for Better Blood Sugar, According to Dietitians",
    description: "These shelf-stable pantry staples are great to have on hand for blood-sugar-friendly meals, snacks and more.",
    url: "https://www.eatingwell.com/best-canned-foods-for-better-blood-sugar-8649708",
    urlToImage: "https://s.yimg.com/ny/api/res/1.2/iWpcX4lmOlqXMAi.UWhytQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MTA-/https://media.zenfs.com/en/eating_well_articles_946/87b62782730e0616bb046304d68f0f01",
    publishedAt: "2024-05-28T15:52:13Z",
    content: "These shelf-stable pantry staples are great to have on hand for blood-sugar-friendly meals, snacks and more.\r\nPhotographer: Jen Causey, Food Stylist: Julian Hensarling, Prop Stylist: Josh Hoggle\r\nRev… [+7536 chars]",
  },
  {
    source: { id: null, name: "WFLA" },
    author: "MARK THIESSEN Associated Press",
    title: "Moose kills man attempting to take photos of her newborn calves",
    description: "A 70-year-old Alaska man who was attempting to take photos of two newborn moose calves was attacked and killed by their mother, authorities said Monday.",
    url: "https://www.wfla.com/news/national/moose-kills-man-attempting-to-take-photos-of-her-newborn-calves/",
    urlToImage: "https://media.zenfs.com/en/wfla_article_174/1204a685b47bc75b630232a00c51c062",
    publishedAt: "2024-05-21T14:10:33Z",
    content: "ANCHORAGE, Alaska (AP) A 70-year-old Alaska man who was attempting to take photos of two newborn moose calves was attacked and killed by their mother, authorities said Monday.\r\nThe man killed Sunday … [+2199 chars]",
  },
  {
    source: { id: null, name: "Cheezburger.com" },
    author: "RemyMill, RemyMill",
    title: "Fish-flops and scuba heels: 25+ Super strange shoes that turn heads wherever they go",
    description:
      "This is fashion, baby. High fashion, low fashion, it doesn't matter to the tastemakers of the world. There's arguably nowhere the fashion scene is more vibrant, experimental, and on full display than New York. Just by walking down the street, you'll encounter…",
    url: "https://cheezburger.com/35212805/fish-flops-and-scuba-heels-25-super-strange-shoes-that-turn-heads-wherever-they-go",
    urlToImage: "https://i.chzbgr.com/thumb1200/35212805/hB16F9701/fish-flops-and-scuba-heels-25-shoes-that-turn-heads-wherever-they-go",
    publishedAt: "2024-06-04T19:00:00Z",
    content: "This is fashion, baby. High fashion, low fashion, it doesn't matter to the tastemakers of the world. There's arguably nowhere the fashion scene is more vibrant, experimental, and on full display than… [+1266 chars]",
  },
  {
    source: { id: "time", name: "Time" },
    author: "MARK THIESSEN / AP",
    title: "Moose Kills Alaska Man Attempting to Take Photos of Her Calves",
    description: "A 70-year-old Alaska man who was attempting to take photos of two newborn moose calves was attacked and killed by their mother.",
    url: "https://time.com/6980392/moose-kills-alaska-man-calves/",
    urlToImage: "https://api.time.com/wp-content/uploads/2024/05/Moose.jpg?quality=85&w=1200&h=628&crop=1",
    publishedAt: "2024-05-21T00:38:55Z",
    content: "(ANCHORAGE, Alaska) A 70-year-old Alaska man who was attempting to take photos of two newborn moose calves was attacked and killed by their mother, authorities said Monday.\r\nThe man killed Sunday was… [+1988 chars]",
  },
  {
    source: { id: null, name: "Thekitchn.com" },
    author: "Kiersten Hickman",
    title: "Aldi Just Brought Back a Fan Favorite $2 Lunch Find",
    description: "We love an easy lunch find!\nREAD MORE...",
    url: "https://www.thekitchn.com/aldi-tinned-herring-fillets-23659109",
    urlToImage: "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_auto,w_1500,ar_3:2/stock%2Fshutterstock_1814289608",
    publishedAt: "2024-05-15T19:15:00Z",
    content: "Tinned fish has been an Aldi fan favorite for years now. However, Aldi only puts these specific tinned fish flavors out when its time for their German Week, a weeklong sale of their favorite German-i… [+459 chars]",
  },
  {
    source: { id: null, name: "Windows Central" },
    author: "ben.wilson@windowscentral.com (Ben Wilson)",
    title: "The most ridiculous CPU cooler I've ever tested is also one of the best — with a cute IPS display and THICC radiator",
    description: 'HYTE, best known for its gigantic "fish tank" PC cases, enters the CPU cooler scene with the THICC Q60 AIO and FP12 case fans — are the extravagant aesthetics worth the high cost?',
    url: "https://www.windowscentral.com/hardware/cpu-gpu-components/hyte-thicc-q60-review",
    urlToImage: "https://cdn.mos.cms.futurecdn.net/gVNBiuzT2wRaHTCycnqq5K-1200-80.jpg",
    publishedAt: "2024-05-09T12:00:00Z",
    content: "HYTE has never been a brand known for subtlety in the custom desktop space, creating some of the most gigantic and extravagant PC cases alongside accessories dripping in enough RGB to make a leprecha… [+12577 chars]",
  },
  {
    source: { id: null, name: "Mental Floss" },
    author: "Jake Rossen",
    title: "“[It] Looked Like a Penis”: The Origin of the Iconic ‘Jaws’ Art",
    description: "A nude swimmer and a phallic-looking fish nearly sunk one of the most recognizable book covers of modern times.",
    url: "https://www.mentalfloss.com/posts/jaws-art-origin",
    urlToImage: "https://images2.minutemediacdn.com/image/upload/c_crop,w_3838,h_2158,x_0,y_0/c_fill,w_1440,ar_16:9,f_auto,q_auto,g_auto/images/voltaxMediaLibrary/mmsport/mentalfloss/01hz7r0bvwbsnx2v375a.jpg",
    publishedAt: "2024-06-03T21:59:00Z",
    content: "The sales managers at Doubleday stared at the screen. Projected from a slide was the proposed cover art to Jaws, a forthcoming thriller novel from an unheralded author named Peter Benchley about an a… [+7133 chars]",
  },
  {
    source: { id: null, name: "ReadWrite" },
    author: "Sophie Atkinson",
    title: "Dave the Diver’s collab with Godzilla is live, but players don’t have long before it’s gone",
    description:
      "Godzilla has officially come to Dave the Diver but he won’t be sticking around for long, as the ancient reptilian… Continue reading Dave the Diver’s collab with Godzilla is live, but players don’t have long before it’s gone\nThe post Dave the Diver’s collab wi…",
    url: "https://readwrite.com/dave-the-divers-collab-with-godzilla-is-live-but-players-dont-have-long-before-its-gone/",
    urlToImage: "https://readwrite.com/wp-content/uploads/2024/05/a8791e1fba02374e1c92835304a0195f653bf2bf.jpg.webp",
    publishedAt: "2024-05-24T12:21:15Z",
    content: "Godzilla has officially come to Dave the Diver but he wont be sticking around for long, as the ancient reptilian beast will be gone from November 23. Players have before then to redeem it, then the e… [+1664 chars]",
  },
  {
    source: { id: null, name: "Science Daily" },
    author: null,
    title: "Scientists find ancient, endangered lamprey fish in Queensland, 1400 km north of its previous known range",
    description: "Scientists have confirmed the identity of an unusual, ancient and Endangered species of fish that is living in the coastal rivers of Queensland, about 1400 km north of where it was previously known to live.",
    url: "https://www.sciencedaily.com/releases/2024/05/240508094858.htm",
    urlToImage: "https://www.sciencedaily.com/images/scidaily-icon.png",
    publishedAt: "2024-05-08T13:48:58Z",
    content: "The Australian brook lamprey (Mordacia praecox) is part of a group of primitive jawless fish. It's up to 15 cm long, with rows of sharp teeth. Surprisingly, it doesn't use these teeth to suck blood l… [+2911 chars]",
  },
  {
    source: { id: "bbc-news", name: "BBC News" },
    author: "https://www.facebook.com/bbcnews",
    title: "Woman says she will sue over Baby Reindeer character",
    description: "Fiona Harvey accuses Netflix, as well as writer Richard Gadd, of lying, in a Piers Morgan interview.",
    url: "https://www.bbc.co.uk/news/entertainment-arts-68975659",
    urlToImage: "https://ichef.bbci.co.uk/news/1024/branded_news/635F/production/_133293452_de29.jpg",
    publishedAt: "2024-05-10T11:45:08Z",
    content: "The woman who has been alleged to have inspired the character Martha in hit drama Baby Reindeer has said she will sue its creator and Netflix.\r\nFiona Harvey told Piers Morgan that the series, in whic… [+4152 chars]",
  },
  {
    source: { id: null, name: "Yahoo Entertainment" },
    author: "Will Shanklin",
    title: "How to watch Summer Games Done Quick 2024",
    description:
      "Summer Games Done Quick (SGDQ) is back for more charity speed runs of classic and contemporary games. The 2024 edition of the marathon will stream from Minneapolis from June 30 to July 6 as turbo-gamers take on Alan Wake II, Halo 3 and the Super Mario RPG rem…",
    url: "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_de6792bc-4393-47aa-8879-983586eacf1f",
    urlToImage: null,
    publishedAt: "2024-06-04T17:20:07Z",
    content: "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]",
  },
  {
    source: { id: null, name: "Miami Herald" },
    author: "Omar Rodríguez Ortiz",
    title: "The search is on for a boater who hit and killed a girl water skiing off Key Biscayne",
    description: "Witnesses or anyone with information are asked to call the Wildlife Alert Hotline at 888-404-3922.",
    url: "https://www.miamiherald.com/news/local/crime/article288463233.html",
    urlToImage: "https://media.zenfs.com/en/miami_herald_mcclatchy_975/7423c7e2424d1767818e6ec7033b4c0a",
    publishedAt: "2024-05-12T00:00:41Z",
    content: "A girl has died after a boat driver hit her and sped away while she was water skiing near Key Biscayne Saturday afternoon, according to the Florida Fish and Wildlife Conservation Commission.\r\nThe gir… [+1076 chars]",
  },
  {
    source: { id: null, name: "Yahoo Entertainment" },
    author: "Chris Oberholtz",
    title: "See it: Catfish 'the size of a 6th grader' tops state record after pulled from Oklahoma reservoir",
    description: "Have you ever encountered a catfish so massive that it rivals the size of your teenager on summer break from middle school?",
    url: "https://www.yahoo.com/news/see-catfish-size-6th-grader-160955627.html",
    urlToImage: "https://s.yimg.com/ny/api/res/1.2/zYDkkREG6PTeEBwaLQ7gGQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/fox_weather_articles_483/5928e703cc6e3698460ac35c96dd99e9",
    publishedAt: "2024-05-30T16:09:55Z",
    content: "VALLIANT, Okla. Have you ever encountered a catfish so massive that it rivals the size of your teenager on summer break from middle school?\r\n\"Not to be too Oklahomish but do y'all wanna see a catfish… [+1237 chars]",
  },
  {
    source: { id: "abc-news", name: "ABC News" },
    author: "MARK THIESSEN Associated Press",
    title: "Moose kills Alaska man attempting to take photos of her newborn calves",
    description: "Authorities in Alaska say a moose has killed a 70-year-old man in the community of Homer",
    url: "https://abcnews.go.com/US/wireStory/moose-kills-alaska-man-attempting-photos-newborn-calves-110416356",
    urlToImage: "https://i.abcnewsfe.com/a/0cd256fa-ef61-44f5-bc88-cd73935fba10/wirestory_3b4aae076c5e29a5d59da9644052cb12_16x9.jpg?w=1600",
    publishedAt: "2024-05-21T00:14:43Z",
    content: "ANCHORAGE, Alaska -- A 70-year-old Alaska man who was attempting to take photos of two newborn moose calves was attacked and killed by their mother, authorities said Monday.\r\nThe man killed Sunday wa… [+1989 chars]",
  },
  {
    source: { id: "abc-news", name: "ABC News" },
    author: "PATRICK WHITTLE Associated Press",
    title: "Beach weather is here and so are sharks. Scientists say it's time to look out for great whites",
    description: "Scientists with a Boston aquarium are encouraging beachgoers to report sightings of white sharks this holiday weekend after signs of shark bites were observed on multiple marine mammals",
    url: "https://abcnews.go.com/US/wireStory/beach-weather-sharks-scientists-time-great-whites-110514718",
    urlToImage: "https://i.abcnewsfe.com/a/7f3aaaa8-e5a5-4008-8d99-804dc2decb77/wirestory_0ad316711eca9737d872412f00720ae7_16x9.jpg?w=1600",
    publishedAt: "2024-05-23T19:50:38Z",
    content: "PORTLAND, Maine -- Scientists with a Boston aquarium are encouraging beachgoers to report sightings of white sharks this holiday weekend after signs of shark bites were observed on multiple marine ma… [+1889 chars]",
  },
  {
    source: { id: null, name: "Thekitchn.com" },
    author: "Su-Jit Lin",
    title: "My Mom’s Clever Trick for Making Vegetables Taste Amazing (I’ve Been Doing It for 25 Years!)",
    description: "Do it once and you'll rely on it forever.\nREAD MORE...",
    url: "https://www.thekitchn.com/two-ingredient-vegetable-seasoning-mom-tip-23659114",
    urlToImage: "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_auto,w_1500,ar_3:2/k%2FEdit%2F2024-05-moms-secret-veggie-seasoning%2Fmoms-secret-veggie-seasoning-15",
    publishedAt: "2024-05-19T14:30:00Z",
    content: "Leave vegetables with a high-water content, like spinach, zucchini, snake squash, cucumbers, Napa cabbage, and Shanghai bok choy, uncovered and cook until the liquid has mostly evaporated. For a bit … [+694 chars]",
  },
  {
    source: { id: null, name: "ReadWrite" },
    author: "Paul McNally",
    title: "New Star Citizen update Adventure Beckons introduces animals, hoverbikes, and much more",
    description:
      "Star Citizen’s latest update, Adventure Beckons goes live today and brings, for the first time to the universe, native wildlife.… Continue reading New Star Citizen update Adventure Beckons introduces animals, hoverbikes, and much more\nThe post New Star Citize…",
    url: "https://readwrite.com/new-star-citizen-update-adventure-beckons-introduces-animals-hoverbikes-and-much-more/",
    urlToImage: "https://readwrite.com/wp-content/uploads/2024/05/star_citizen_adventure_begins.jpg",
    publishedAt: "2024-05-13T14:32:44Z",
    content: "Star Citizens latest update, Adventure Beckons goes live today and brings, for the first time to the universe, native wildlife. More and more content from Squadron 42 is gradually being incorporated … [+1866 chars]",
  },
  {
    source: { id: null, name: "BBC News" },
    author: null,
    title: "Fatal black bear attack a first in California history",
    description: "A woman found dead in her home was initially thought to have died before the animal's arrival.",
    url: "https://www.bbc.com/news/articles/cw445jn5pqpo",
    urlToImage: "https://ichef.bbci.co.uk/news/1024/branded_news/bae2/live/675716e0-24c6-11ef-a13a-0b8c563da930.jpg",
    publishedAt: "2024-06-07T12:07:48Z",
    content: "By Brandon Drenon, BBC News, Washington DC\r\nA 71-year-old woman found dead in her home is determined to have been killed by a black bear, in the first known fatal attack by one of the animals in Cali… [+1773 chars]",
  },
  {
    source: { id: null, name: "Rock Paper Shotgun" },
    author: "Nic Reuben",
    title: "This game will be deleted from Steam unless players can beat the developers at it",
    description:
      "Back in 2020, fresh out of high school and feeling unstoppable, Charles Maddock and a few friends “decided to code a game about Fish Wizards.” The result was Fishards, Magicka-inspired PVP arena action that has you out-squirt, out-splash, and out-spellcast yo…",
    url: "https://www.rockpapershotgun.com/this-game-will-be-deleted-from-steam-unless-players-can-beat-the-developers-at-it",
    urlToImage: "https://assetsio.gnwcdn.com/fishards-1.jpg?width=1200&height=630&fit=crop&enable=upscale&auto=webp",
    publishedAt: "2024-06-07T08:43:37Z",
    content: "Back in 2020, fresh out of high school and feeling unstoppable, Charles Maddock and a few friends “decided to code a game about Fish Wizards.” The result was Fishards, Magicka-inspired PVP arena acti… [+1869 chars]",
  },
  {
    source: { id: null, name: "Semafor.com" },
    author: "Tom Chivers",
    title: "SHOCK CLAIM: FISH ARE shrinking...",
    description: "The average body weight of nearly three-quarters of marine fish populations sampled dropped between 1960 and 2020, a recent study suggests.",
    url: "https://www.semafor.com/article/05/08/2024/fish-shrinking-overfishing-climate-change",
    urlToImage: "https://img.semafor.com/61676777687a9eb8066b81ee4f09245691fcc2e5-1280x854.png?rect=0,25,1280,672&w=1200&h=630&q=75&auto=format",
    publishedAt: "2024-05-08T15:43:36Z",
    content: "Fish are shrinking. The average body weight of nearly three-quarters of marine fish populations sampled dropped between 1960 and 2020, a recent study suggests.\r\nThe change threatens the food supply o… [+472 chars]",
  },
  {
    source: { id: null, name: "IndieWire" },
    author: "Samantha Bergeson",
    title: "Frameline 2024 Highlights Include Lena Waithe and ‘Go Fish’ 4K Restoration",
    description: "The Frameline 2024 lineup include Lena Waithe and 'Go Fish' 4K restoration.",
    url: "https://www.indiewire.com/news/general-news/frameline-2024-lineup-1235007433/",
    urlToImage: "https://www.indiewire.com/wp-content/uploads/2024/03/MSDGOFI_EC003.jpg?w=650",
    publishedAt: "2024-05-22T15:00:36Z",
    content: "The 48th annual San Francisco International LGBTQ+ Film Festival, hosted by arts nonprofit  Frameline48, has officially unveiled its lineup. \r\nThe longest-running LGBTQ+ film festival in the world wi… [+10969 chars]",
  },
  {
    source: { id: null, name: "Science Daily" },
    author: null,
    title: "The embryo assembles itself",
    description:
      "Biological processes depend on puzzle pieces coming together and interacting. Under specific conditions, these interactions can create something new without external input. This is called self-organization, as seen in a school of fish or a flock of birds. Int…",
    url: "https://www.sciencedaily.com/releases/2024/06/240603114353.htm",
    urlToImage: "https://www.sciencedaily.com/images/scidaily-icon.png",
    publishedAt: "2024-06-03T15:43:53Z",
    content: "Biological processes depend on puzzle pieces coming together and interacting. Under specific conditions, these interactions can create something new without external input. This is called self-organi… [+4752 chars]",
  },
  {
    source: { id: null, name: "Schneier.com" },
    author: "Bruce Schneier",
    title: "Online Privacy and Overfishing",
    description:
      "Microsoft recently caught state-backed hackers\r\n using its generative AI tools to help with their attacks. In the security community, the immediate questions weren’t about how hackers were using the tools (that was utterly predictable), but about how Microsof…",
    url: "https://www.schneier.com/blog/archives/2024/06/online-privacy-and-overfishing.html",
    urlToImage: null,
    publishedAt: "2024-06-04T08:34:52Z",
    content: "Microsoft recently caught state-backed hackers\r\n using its generative AI tools to help with their attacks. In the security community, the immediate questions weren’t about how hackers were using the … [+5193 chars]",
  },
  {
    source: { id: null, name: "Knowablemagazine.org" },
    author: "Amber Dance",
    title: "Spots, stripes and more: Working out the logic of animal patterns",
    description:
      "More than 70 years ago, mathematician Alan Turing proposed a mechanism that explained how patterns could emerge from bland uniformity. Scientists are still using his model — and adding new twists — to gain a deeper understanding of animal markings.",
    url: "https://knowablemagazine.org/content/article/living-world/2024/animal-patterns-spots-stripes-explained-turing-mechanism",
    urlToImage: "https://knowablemagazine.org/docserver/fulltext/animal-patterns-1600x600.jpg",
    publishedAt: "2024-05-29T23:50:24Z",
    content: "Theres a reason fashion designers look to animal prints for inspiration. Creatures have evolved a dizzying array of patterns: stripes, spots, diamonds, chevrons, hexagons and even mazelike designs. S… [+15172 chars]",
  },
  {
    source: { id: null, name: "Phys.Org" },
    author: "Rosalio Ahumada, The Sacramento Bee",
    title: "California bans salmon fishing for the season in Sacramento-area rivers and Klamath basin",
    description: "The California Fish and Game Commission has voted to ban salmon fishing in the Sacramento, American, Feather and Mokelumne rivers.",
    url: "https://phys.org/news/2024-05-california-salmon-fishing-season-sacramento.html",
    urlToImage: "https://scx2.b-cdn.net/gfx/news/hires/2019/4-salmon.jpg",
    publishedAt: "2024-05-20T16:36:02Z",
    content: "The California Fish and Game Commission has voted to ban salmon fishing in the Sacramento, American, Feather and Mokelumne rivers.\r\nThis is the second consecutive year the commission has voted to ban… [+2103 chars]",
  },
  {
    source: { id: null, name: "Phys.Org" },
    author: "Cynthia McCormick Hibbert",
    title: "Microplastics may slow the rate at which carbon is pulled from the sea surface to the depths",
    description: "It turns out plastics in the ocean do more than suffocate turtles, fish and other marine life.",
    url: "https://phys.org/news/2024-05-microplastics-carbon-sea-surface-depths.html",
    urlToImage: "https://scx2.b-cdn.net/gfx/news/2024/microplastics-may-slow.jpg",
    publishedAt: "2024-05-17T15:36:03Z",
    content:
      "This article has been reviewed according to Science X's \r\neditorial process\r\nand policies.\r\nEditors have highlighted\r\nthe following attributes while ensuring the content's credibility:\r\nfact-checked\r… [+3964 chars]",
  },
  {
    source: { id: null, name: "Skinnytaste.com" },
    author: "Gina",
    title: "Grape Tomato Sauce",
    description:
      "When grape tomatoes are overflowing in your garden, whip up a quick, easy tomato sauce! Grape or cherry tomatoes sauteed with olive oil, garlic, and fresh herbs are perfect over pasta, grilled chicken, or fish. Easy Grape Tomato Sauce I make this simple grape…",
    url: "https://www.skinnytaste.com/easy-garden-tomato-sauce/",
    urlToImage: "https://www.skinnytaste.com/wp-content/uploads/2012/07/Easy-Garden-Tomato-Sauce-7-scaled.jpg",
    publishedAt: "2024-05-29T19:57:11Z",
    content: "This post may contain affiliate links. Read my disclosure policy.\r\nWhen grape tomatoes are overflowing in your garden, whip up a quick, easy tomato sauce! Grape or cherry tomatoes sauteed with olive … [+4413 chars]",
  },
  {
    source: { id: null, name: "Phys.Org" },
    author: "Science X",
    title: "Fish out of water: How killifish embryos adapt their development",
    description:
      "The annual killifish lives in regions with extreme drought. A research group at the University of Basel now reports in Science that the early embryogenesis of killifish diverges from that of other species. Unlike other fish, their body structure is not predet…",
    url: "https://phys.org/news/2024-06-fish-killifish-embryos.html",
    urlToImage: "https://scx2.b-cdn.net/gfx/news/hires/2024/fish-out-of-water-how.jpg",
    publishedAt: "2024-06-06T18:00:01Z",
    content: "This article has been reviewed according to Science X's \r\neditorial process\r\nand policies.\r\nEditors have highlighted\r\nthe following attributes while ensuring the content's credibility:\r\nfact-checked\r… [+425 chars]",
  },
  {
    source: { id: null, name: "ReadWrite" },
    author: "Eric Dunne",
    title: "Is It Time To Sell 38% Render Gains And Buy $Kai Cat?",
    description:
      "Tokens for the Render Network (RNDR) were up 38% on the 7-day window ending Wednesday evening U.S. Central Time in… Continue reading Is It Time To Sell 38% Render Gains And Buy $Kai Cat?\nThe post Is It Time To Sell 38% Render Gains And Buy $Kai Cat? appeared …",
    url: "https://readwrite.com/is-it-time-to-sell-38-render-gains-and-buy-kai-cat/",
    urlToImage: "https://readwrite.com/wp-content/uploads/2024/05/Render-Price-Chart-.jpg",
    publishedAt: "2024-05-24T04:07:03Z",
    content: "Tokens for the Render Network (RNDR) were up 38% on the 7-day window ending Wednesday evening U.S. Central Time in a week that AI cryptocurrencies absolutely dominated the coin leaderboards. The only… [+2965 chars]",
  },
  {
    source: { id: null, name: "Search Engine Journal" },
    author: "Roger Montti",
    title: "Google Is Now Indexing EPUB Files via @sejournal, @martinibuster",
    description: "Google quietly started indexing EPUB files and can now be seen in the SERPs\nThe post Google Is Now Indexing EPUB Files appeared first on Search Engine Journal.",
    url: "https://www.searchenginejournal.com/google-is-now-indexing-epub-files/517586/",
    urlToImage: "https://www.searchenginejournal.com/wp-content/uploads/2024/05/google-indexing-epub-files-109.jpg",
    publishedAt: "2024-05-28T02:35:47Z",
    content: "Google announced that it is now indexing .epub documents, a format commonly used to print books for e-readers. Google is already showing EPUB books in the search index.\r\nEPUB File Format\r\nEPUB is an … [+1853 chars]",
  },
  {
    source: { id: null, name: "ReadWrite" },
    author: "Owen Good",
    title: "Hellblade II reviews roundup: If critics agree on anything, it’s visually impressive",
    description:
      "Senua’s Saga: Hellblade 2 launched on May 21, with reviews of Ninja Theory’s Xbox Series X and Windows PC exclusive… Continue reading Hellblade II reviews roundup: If critics agree on anything, it’s visually impressive\nThe post Hellblade II reviews roundup: I…",
    url: "https://readwrite.com/hellblade-ii-review-scores-metacritic-hours-should-you-play/",
    urlToImage: "https://readwrite.com/wp-content/uploads/2024/03/de96a24e-cb77-42c7-b28a-334d1f51b299.jpg",
    publishedAt: "2024-05-21T19:51:16Z",
    content: "Senuas Saga: Hellblade 2 launched on May 21, with reviews of Ninja Theorys Xbox Series X and Windows PC exclusive coming in the dame day. Microsoft is looking to the game to drive value to its Xbox G… [+3239 chars]",
  },
  {
    source: { id: null, name: "Thekitchn.com" },
    author: "Stephanie Ganz",
    title: "This $3 Duke’s Sauce Is Even Better Than Its Legendary Mayonnaise",
    description: "It’s a kicked-up version of a classic.\nREAD MORE...",
    url: "https://www.thekitchn.com/dukes-bayou-remoulade-review-23661266",
    urlToImage: "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_auto,w_1500,ar_3:2/k%2FEdit%2Fcropped-fried-oysters-2",
    publishedAt: "2024-05-29T14:30:00Z",
    content: "We independently select these products—if you buy from one of our links, we may earn a commission. All prices were accurate at the time of publishing.\r\nI am, proudly, a condiment queen. Im constantly… [+2473 chars]",
  },
  {
    source: { id: "ars-technica", name: "Ars Technica" },
    author: "Elizabeth Rayne",
    title: "Bizarre egg-laying mammals once ruled Australia—then lost their teeth",
    description: "Finds may indicate what the common ancestor of the platypus and echidna looked like.",
    url: "https://arstechnica.com/science/2024/06/bizarre-egg-laying-mammals-once-ruled-australia-then-lost-their-teeth/",
    urlToImage: "https://cdn.arstechnica.net/wp-content/uploads/2024/06/GettyImages-1130236100-760x380.jpg",
    publishedAt: "2024-06-07T18:25:11Z",
    content: "Enlarge/ The echidna, an egg-laying mammal, doesn't develop teeth.\r\n5\r\nOutliers among mammals, monotremes lay eggs instead of giving birth to live young. Only two types of monotremes, the platypus an… [+5260 chars]",
  },
  {
    source: { id: null, name: "Wikihow.com" },
    author: "Trudi Griffin, LPC, MS",
    title: "How to Act Confident",
    description:
      "Most people feel confident in some situations, but not in others. Perhaps you feel confident in school because you have good grades. When you’re at a party, however, you feel like a fish out of water and you become shy and unconfident. Or maybe you feel confi…",
    url: "https://www.wikihow.com/Act-Confident",
    urlToImage: "https://www.wikihow.com/images/b/b1/Act-Confident-Step-29-Version-2.jpg",
    publishedAt: "2024-05-18T08:00:00Z",
    content: "This article was co-authored by Trudi Griffin, LPC, MS. Trudi Griffin is a Licensed Professional Counselor in Wisconsin specializing in Addictions and Mental Health. She provides therapy to people wh… [+526 chars]",
  },
  {
    source: { id: null, name: "Phys.Org" },
    author: "Andrew Sheeler, The Sacramento Bee",
    title: "An 'unusually high number' of emaciated California brown pelicans are turning up on shore",
    description: "Large numbers of California brown pelicans are turning up on shore with signs of malnutrition, prompting a California Department of Fish and Wildlife investigation.",
    url: "https://phys.org/news/2024-05-unusually-high-emaciated-california-brown.html",
    urlToImage: "https://scx2.b-cdn.net/gfx/news/hires/2024/california-brown-pelic.jpg",
    publishedAt: "2024-05-13T16:10:01Z",
    content: "Large numbers of California brown pelicans are turning up on shore with signs of malnutrition, prompting a California Department of Fish and Wildlife investigation.\r\nCalifornia brown pelicans are a f… [+1797 chars]",
  },
  {
    source: { id: null, name: "Phys.Org" },
    author: "Science X",
    title: "A pregnant stingray with no male companion now has a 'reproductive disease,' aquarium says",
    description: "A North Carolina aquarium that said it had a pregnant stingray with no male companion now says the fish has a rare reproductive disease.",
    url: "https://phys.org/news/2024-05-pregnant-stingray-male-companion-reproductive.html",
    urlToImage: "https://scx2.b-cdn.net/gfx/news/hires/2024/a-pregnant-stingray-wi.jpg",
    publishedAt: "2024-05-31T16:41:30Z",
    content: "Charlotte, a round stingray, in an undated photo at the Aquarium and Shark Lab by Team ECCO in Hendersonville, N.C. The aquarium that said it had Charlotte, a pregnant stingray with no male companion… [+2283 chars]",
  },
  {
    source: { id: null, name: "Phys.Org" },
    author: "Science X",
    title: "The importance of the paradise fish in evolutionary and behavioral genetics research",
    description:
      "In Hungary, ethological research is most often identified with tests on dogs, but novel methodological advances could bring another species, the paradise fish, into the spotlight. Fish are easy to handle and produce numerous offspring, which could open up new…",
    url: "https://phys.org/news/2024-06-importance-paradise-fish-evolutionary-behavioral.html",
    urlToImage: "https://scx2.b-cdn.net/gfx/news/hires/2024/the-importance-of-the-1.jpg",
    publishedAt: "2024-06-05T21:33:03Z",
    content:
      "This article has been reviewed according to Science X's \r\neditorial process\r\nand policies.\r\nEditors have highlighted\r\nthe following attributes while ensuring the content's credibility:\r\nfact-checked\r… [+3506 chars]",
  },
  {
    source: { id: null, name: "CNET" },
    author: "David Watsky",
    title: "Here's How Much It Costs to Have Groceries Delivered Versus Buying In Person - CNET",
    description: "Convenience has its cost. We crunched the numbers to see exactly what that cost is.",
    url: "https://www.cnet.com/home/kitchen-and-household/heres-how-much-it-costs-to-have-groceries-delivered-versus-shopping-in-person/",
    urlToImage: "https://www.cnet.com/a/img/resize/49ce944913da091b0284585e7e72a317257457fa/hub/2022/10/28/1e73bac8-17b5-4de2-97e1-9f50cdf89c49/screen-shot-2022-10-28-at-10-30-25-am.png?auto=webp&fit=crop&height=675&width=1200",
    publishedAt: "2024-05-22T17:29:00Z",
    content: "Grocery delivery is the pinnacle of modern delivery. Instead of wandering the aisles of your supermarket in search of cream of mushroom soup and cauliflower rice, you compile an entire list of grocer… [+15591 chars]",
  },
  {
    source: { id: null, name: "Github.com" },
    author: "andyk",
    title: "ht: Headless Terminal",
    description: "headless terminal - wrap any binary with a terminal interface for easy programmatic access. - andyk/ht",
    url: "https://github.com/andyk/ht",
    urlToImage: "https://opengraph.githubassets.com/a5a1c6503195a510c1bb0e7455eb5921f5de3e51585ce09e52d211680fd7ab58/andyk/ht",
    publishedAt: "2024-06-02T07:53:14Z",
    content: "ht (short for headless terminal) is a command line program that wraps an arbitrary other binary (e.g. bash, vim, etc.) with a VT100 style terminal interface--i.e. a pseudoterminal client (PTY) plus t… [+3398 chars]",
  },
  {
    source: { id: null, name: "CNET" },
    author: "David Watsky",
    title: "You Could Probably Make This Air Fryer Salmon With Your Eyes Closed - CNET",
    description: "It's that easy.",
    url: "https://www.cnet.com/home/kitchen-and-household/you-could-probably-make-this-air-fryer-salmon-with-your-eyes-closed/",
    urlToImage: "https://www.cnet.com/a/img/resize/c3491cdf0de77232f8f01a5854ad1974eede6c54/hub/2024/05/02/b11f766b-44af-4e32-9632-e34c3ffe78c3/screenshot-2024-05-02-at-1-31-36pm.png?auto=webp&fit=crop&height=675&width=1200",
    publishedAt: "2024-05-21T21:39:00Z",
    content: "Every year, I find a few new ways to use the air fryer. It never ceases to amaze me how well and quickly the air fryer cooks food and how simple it is to clean after. For super simple, healthy weekni… [+3041 chars]",
  },
  {
    source: { id: null, name: "Xataka.com" },
    author: "John Tones",
    title: "Es la mejor película de Tim Burton, muy pronto estrena una secuela que se ha hecho esperar 36 años, y la tienes en Max",
    description:
      "Ni 'Eduardo Manostijeras', ni 'Batman vuelve', ni 'Big Fish'. Para el que suscribe, 'Bitelchús' (que puedes ver en Max y en Movistar Plus+) es el summun del ingenio de Tim Burton. Una mezcla absolutamente impecable de terror y comedia con el sello personal -a…",
    url: "https://www.xataka.com/streaming/mejor-pelicula-tim-burton-muy-pronto-estrena-secuela-que-se-ha-hecho-esperar-36-anos-tienes-max",
    urlToImage: "https://i.blogs.es/4636d6/captura-de-pantalla-2024-05-29-a-las-18.19.24/840_560.jpeg",
    publishedAt: "2024-05-29T18:15:59Z",
    content: "Ni 'Eduardo Manostijeras', ni 'Batman vuelve', ni 'Big Fish'. Para el que suscribe, 'Bitelchús' (que puedes ver en Max y en Movistar Plus+) es el summun del ingenio de Tim Burton. Una mezcla absoluta… [+1980 chars]",
  },
  {
    source: { id: null, name: "Cheezburger.com" },
    author: "RemyMill, RemyMill",
    title: "'It is a very small issue in the gran stephen things': 20 Hilarious misspellings and misunderstandings",
    description:
      'I know most of us aren\'t good spellers—thank goodness for autocorrect! Without it, we\'d never spell words like "necessity" or "appreciation" correctly. Without spell checkers, it\'d be a lot harder to read just about everything. You can certainly tell that fro…',
    url: "https://cheezburger.com/35232261/it-is-a-very-small-issue-in-the-gran-stephen-things-20-hilarious-misspellings-and-misunderstandings",
    urlToImage: "https://i.chzbgr.com/thumb1200/35232261/h38BD995A/it-is-a-very-small-issue-in-the-gran-stephen-things-20-hilarious-misspellings-and-misunderstandings",
    publishedAt: "2024-06-05T19:00:00Z",
    content: 'I know most of us aren\'t good spellersthank goodness for autocorrect! Without it, we\'d never spell words like "necessity" or "appreciation" correctly. Without spell checkers, it\'d be a lot harder to … [+731 chars]',
  },
  {
    source: { id: null, name: "Skinnytaste.com" },
    author: "Gina",
    title: "Free 7 Day Healthy Meal Plan (June 10-16)",
    description:
      "A free 7-day, flexible weight loss meal plan including breakfast, lunch and dinner ideas and a shopping list. All recipes include macros and Weight Watchers points. Free 7 Day Healthy Meal Plan (June 10-16) Let’s get that grill fired up and ready to celebrate…",
    url: "https://www.skinnytaste.com/free-7-day-healthy-meal-plan-june-10-16/",
    urlToImage: "https://www.skinnytaste.com/wp-content/uploads/2024/06/Week_438_june-10-June-16.jpg",
    publishedAt: "2024-06-07T15:54:51Z",
    content: "This post may contain affiliate links. Read my disclosure policy.\r\nA free 7-day, flexible weight loss meal plan including breakfast, lunch and dinner ideas and a shopping list. All recipes include ma… [+9494 chars]",
  },
  {
    source: { id: null, name: "Phys.Org" },
    author: "Science X",
    title: "Novel virus identified in zebrafish from the pet trade causes disease in laboratory fish",
    description:
      "Zebrafish in the pet trade are asymptomatic carriers of previously undescribed microbes, including a novel virus that causes hemorrhaging in infected laboratory fish, Marlen Rice from the University of Utah, US, and colleagues report in the open-access journa…",
    url: "https://phys.org/news/2024-05-virus-zebrafish-pet-disease-laboratory.html",
    urlToImage: "https://scx2.b-cdn.net/gfx/news/hires/2024/novel-virus-identified.jpg",
    publishedAt: "2024-05-30T18:00:01Z",
    content: "Zebrafish in the pet trade are asymptomatic carriers of previously undescribed microbes, including a novel virus that causes hemorrhaging in infected laboratory fish, Marlen Rice from the University … [+2950 chars]",
  },
  {
    source: { id: null, name: "Phys.Org" },
    author: "Science X",
    title: "How do you know where a fish goes? Scientists address gaps in marine animal tracking data",
    description:
      'When scientists want to study the long-distance movement of marine animals, they will instrument them with a small device called an acoustic transmitter—or tag—which emits unique signals or "pings." These signals are picked up by receivers anchored to the sea…',
    url: "https://phys.org/news/2024-06-fish-scientists-gaps-marine-animal.html",
    urlToImage: "https://scx2.b-cdn.net/gfx/news/hires/2024/how-do-you-know-where.jpg",
    publishedAt: "2024-06-06T15:30:04Z",
    content:
      "This article has been reviewed according to Science X's \r\neditorial process\r\nand policies.\r\nEditors have highlighted\r\nthe following attributes while ensuring the content's credibility:\r\nfact-checked\r… [+4466 chars]",
  },
  {
    source: { id: null, name: "Universe Today" },
    author: "Scott Alan Johnston",
    title: "Fish are Adapting to Weightlessness on the Chinese Space Station",
    description:
      "Four zebrafish are alive and well after nearly a month in space aboard China’s Tiangong space station. As part of an experiment testing the development of vertebrates in microgravity, the fish live and swim within a small habitat aboard the station. While the…",
    url: "https://www.universetoday.com/167115/fish-are-adapting-to-weightlessness-on-the-chinese-space-station/",
    urlToImage: "https://www.universetoday.com/wp-content/uploads/2024/05/Zebrafisch.jpg",
    publishedAt: "2024-05-24T19:24:38Z",
    content: "Four zebrafish are alive and well after nearly a month in space aboard China’s Tiangong space station. As part of an experiment testing the development of vertebrates in microgravity, the fish live a… [+2742 chars]",
  },
  {
    source: { id: null, name: "Phys.Org" },
    author: "Science X",
    title: "'Open gates' in warming Arctic are expanding salmon range",
    description: "New research has connected warming ocean temperatures to higher Pacific salmon abundance in the Canadian Arctic, an indicator that climate change is creating new corridors for the fish to expand their range.",
    url: "https://phys.org/news/2024-06-gates-arctic-salmon-range.html",
    urlToImage: "https://scx2.b-cdn.net/gfx/news/hires/2024/open-gates-in-warming.jpg",
    publishedAt: "2024-06-05T09:10:02Z",
    content: "New research has connected warming ocean temperatures to higher Pacific salmon abundance in the Canadian Arctic, an indicator that climate change is creating new corridors for the fish to expand thei… [+4177 chars]",
  },
  {
    source: { id: "vice-news", name: "Vice News" },
    author: "VICE Staff, VICE Staff",
    title: "'Let It Kill You': A New VICE Doc Series About Skateboarding and Art",
    description: "The show dives into the art and skateboarding careers of Ryan Townley, Mike Gigliotti, Michael Sieben and more.",
    url: "https://www.vice.com/en/article/n7eyeq/let-it-kill-you-a-new-vice-doc-series-about-skateboarding-and-art",
    urlToImage: "https://video-images.vice.com/articles/66460a8d92df1f5a72cdd9d8/lede/1715866706222-liky-mike-lottie-c-a-eclov-6.jpeg?image-resize-opts=Y3JvcD0xeHc6MC44NDM3NXhoO2NlbnRlcixjZW50ZXImcmVzaXplPTEyMDA6KiZyZXNpemU9MTIwMDoq",
    publishedAt: "2024-05-17T14:50:19Z",
    content: "Is skateboarding art? This question is incredibly boring to consider, so thank god some skaters have taken it off the table by doing both and not worrying if theyre the same thing. This arrangement i… [+1094 chars]",
  },
  {
    source: { id: "abc-news", name: "ABC News" },
    author: "The Associated Press",
    title: "Woman's 2023 death was first fatal black bear attack on a human in California records, officials say",
    description: "A woman found dead last year in a mountain community was the victim of the first documented fatal black bear attack on a human in California",
    url: "https://abcnews.go.com/US/wireStory/womans-2023-death-fatal-black-bear-attack-human-110908641",
    urlToImage: "https://s.abcnews.com/images/US/abc_news_default_2000x2000_update_16x9_992.jpg",
    publishedAt: "2024-06-06T19:29:26Z",
    content: "DOWNIEVILLE, Calif. -- A woman found dead last year in a mountain community was the victim of the first documented fatal black bear attack on a human in California, authorities said.\r\nThe death occur… [+2113 chars]",
  },
  {
    source: { id: null, name: "Yahoo Entertainment" },
    author: "Joyce Lupiani",
    title: "Bartow County I-75 crash: 21-year-old Cartersville resident to be buried Friday",
    description: "The 21-year-old from Cartersville killed on May 19 in the multi-vehicle crash on Interstate 75 in Bartow County will be buried on Friday, May 24.",
    url: "https://www.yahoo.com/news/bartow-county-75-crash-21-193056817.html",
    urlToImage: "https://s.yimg.com/ny/api/res/1.2/1ygLJvgXrAHvU9cRhCTb3g--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/waga_fox_local_articles_107/14d394d14d884697291b3cf9eedca929",
    publishedAt: "2024-05-22T19:30:56Z",
    content: "CARTERSVILLE, Ga. - The 21-year-old from Cartersville killed on May 19 in the multi-vehicle crash on Interstate 75 in Bartow County will be buried on Friday, May 24.\r\nAimee Odom was born in Rome and … [+2631 chars]",
  },
  {
    source: { id: null, name: "Science Daily" },
    author: null,
    title: "Killer whales breathe just once between dives, study confirms",
    description:
      "A new study has confirmed a long-held assumption: that orcas take just one breath between dives. The researchers used drone footage and biological data from tags suction-cupped to 11 northern and southern resident killer whales off the coast of B.C. to gather…",
    url: "https://www.sciencedaily.com/releases/2024/05/240515164215.htm",
    urlToImage: "https://www.sciencedaily.com/images/scidaily-icon.png",
    publishedAt: "2024-05-15T20:42:15Z",
    content: "A new study has confirmed a long-held assumption: that orcas take just one breath between dives.The researchers used drone footage and biological data from tags suction-cupped to 11 northern and sout… [+1544 chars]",
  },
  {
    source: { id: null, name: "Stereogum" },
    author: "Tom Breihan",
    title: "“Fish Market” Lawsuit Can Move Forward With Claim That Over 1,800 Reggaetón Songs Ripped Off Steely & Clevie Riddim",
    description:
      "The entire genre of reggaeton is built on a single beat, a syncopated but militaristic drum pattern known as the dembow riddim. Over the past few decades, reggaeton has emerged from a regional Spanish-language style to a global commercial powerhouse. So what’…",
    url: "https://www.stereogum.com/2265690/fish-market-lawsuit-can-move-forward-with-claim-that-over-1800-reggaeton-songs-ripped-off-steely-clevie-riddim/news/",
    urlToImage: "https://static.stereogum.com/uploads/2024/05/Fish-Market-1717070862.jpg",
    publishedAt: "2024-05-30T12:39:39Z",
    content: "The entire genre of reggaeton is built on a single beat, a syncopated but militaristic drum pattern known as the dembow riddim. Over the past few decades, reggaeton has emerged from a regional Spanis… [+3612 chars]",
  },
  {
    source: { id: null, name: "Space.com" },
    author: "Samantha Mathewson",
    title: "Just keep swimming! Zebrafish doing fine in zero gravity on China's Tiangong space station (video)",
    description: "The four zebrafish China sent to its space station are thriving after spending almost a month in orbit.",
    url: "https://www.space.com/china-tiangong-space-station-zebrafish-healthy",
    urlToImage: "https://cdn.mos.cms.futurecdn.net/zPshUFUmyRSowjRdSpsqkm-1200-80.gif",
    publishedAt: "2024-05-28T15:00:04Z",
    content: "The four zebrafish China sent to its space station are thriving after spending almost a month in orbit. \r\nLaunched on April 25 alongside three astronauts aboard the Shenzhou-18 spacecraft, the zebraf… [+3091 chars]",
  },
  {
    source: { id: null, name: "NPR" },
    author: "Suzanne Nuyen",
    title: "Israel strikes U.N-run school in Gaza; a Georgia clinic cares for the uninsured",
    description: "Israel launched an airstrike on a U.N.-run school in Gaza as part of a new ground and air operation. A health clinic in Georgia specializes in caring for the uninsured.",
    url: "https://www.npr.org/2024/06/06/g-s1-3133/up-first-newsletter-israel-gaza-un-school-airstrike-insurance-health-care",
    urlToImage:
      "https://npr.brightspotcdn.com/dims3/default/strip/false/crop/6720x3780+0+428/resize/1400/quality/100/format/jpeg/?url=http%3A%2F%2Fnpr-brightspot.s3.amazonaws.com%2Fcf%2F73%2Ff5a1e843484b896ee1b85fcee401%2Fap24158296516406.jpg",
    publishedAt: "2024-06-06T12:06:27Z",
    content: "Good morning. You're reading the Up First newsletter. Subscribe here to get it delivered to your inbox, and listen to the Up First podcast for all the news you need to start your day.\r\nToday's top st… [+4554 chars]",
  },
  {
    source: { id: null, name: "KTLA Los Angeles" },
    author: "Travis Schlepp",
    title: "Ocean closed to beachgoers after ‘aggressive’ shark sightings in San Clemente",
    description: "The ocean was closed off to all beachgoers in San Clemente Monday after officials confirmed “aggressive shark behavior” just off the coast. The sharks were...",
    url: "https://ktla.com/news/local-news/ocean-closed-to-beachgoers-after-aggressive-shark-sightings-in-san-clemente/",
    urlToImage: "https://media.zenfs.com/en/ktla_articles_362/45ead6bc49759225435ee3940c1f6935",
    publishedAt: "2024-05-27T21:29:53Z",
    content: "The ocean was closed off to all beachgoers in San Clemente Monday after officials confirmed aggressive shark behavior just off the coast.\r\nThe sharks were spotted near T-Street Beach, according to a … [+1308 chars]",
  },
  {
    source: { id: "business-insider", name: "Business Insider" },
    author: "Tim Paradis",
    title: "Why you might want to lay out your résumé using this method",
    description: "Setting up your résumé using the F-method might help recruiters get to the most important information quickly — and help you stand out.",
    url: "https://www.businessinsider.com/this-method-may-help-resume-stand-out-recruiter-job-search-2024-5",
    urlToImage: "https://i.insider.com/6650dd27239fda2da6cb982d?width=1200&format=jpeg",
    publishedAt: "2024-05-25T09:47:01Z",
    content: "Making your résumé easy to scan can help recruiters get to the key ideas quickly.Alex Slitz/Associated Press\r\n<ul><li>The F-method helps recruiters identify key info by structuring résumés for how th… [+4705 chars]",
  },
  {
    source: { id: "business-insider", name: "Business Insider" },
    author: "Ellyn Lapointe,Morgan McFall-Johnsen",
    title: "2 teens won $50,000 for inventing a device that can filter toxic microplastics from water",
    description: "Two 17-year-olds created the first device to successfully filter microplastics from water using ultrasonic sound waves and won $50,000 for their work.",
    url: "https://www.businessinsider.com/teens-win-fifty-thousand-for-ultrasound-microplastic-filtration-device-2024-5",
    urlToImage: "https://i.insider.com/664fc322a961b37edf398a0a?width=1200&format=jpeg",
    publishedAt: "2024-05-23T23:33:04Z",
    content: "Victoria Ou (right) and Justin Huang (middle) won first place in their category and also snagged one of the top $50,000 prizes for their invention.Society for Science/Chris Ayers\r\n<ul><li>Victoria Ou… [+6095 chars]",
  },
  {
    source: { id: "business-insider", name: "Business Insider" },
    author: "Erin McDowell",
    title: "Photos show what it was like to eat at McDonald's in the 1970s",
    description: "By the 1970s, McDonald's had grown into an increasingly popular fast-food establishment. The first drive-thru was introduced in 1975.",
    url: "https://www.businessinsider.com/vintage-photos-mcdonalds-restaurant-food-menu-1970s",
    urlToImage: "https://i.insider.com/64b194f39751e300192a2aad?width=1200&format=jpeg",
    publishedAt: "2024-05-24T14:22:57Z",
    content: "Product shot of a McDonald's Big Mac hamburger in 1977.Henry Groskinsky/The LIFE Images Collection/Getty Images\r\n<ul>\n<li>The first McDonald's franchise opened in Des Plaines, Illinois, on April 15, … [+6029 chars]",
  },
  {
    source: { id: "business-insider", name: "Business Insider" },
    author: "Emmaline Windeler",
    title: "Google Translate can interpret more than just text. Here's how to use it with text, speech, and images in 100+ languages.",
    description: "Google Translate can translate 133 languages. Millions use the free app daily on iOS and Android. Here's how to translate text, speech, and images.",
    url: "https://www.businessinsider.com/google-translate",
    urlToImage: "https://i.insider.com/664e3e9014fb5b23cc5f4c77?width=1200&format=jpeg",
    publishedAt: "2024-05-24T08:19:01Z",
    content: "SOPA Images/Getty Images\r\n<ul><li>Google Translate supports 133 languages and can translate text, audio, or images.</li><li>You can type or speak into the Google Translate app, or even take a picture… [+5772 chars]",
  },
  {
    source: { id: null, name: "Rock Paper Shotgun" },
    author: "Edwin Evans-Thirlwell",
    title: "Overwatchy FPS Concord gets new trailer and August PC release date with a beta in July",
    description:
      "Sony have dropped a trailer and release date for Concord, a new 5V5 multiplayer FPS in which you play a bunch of freegans carrying out heists (divided into six modes) on various loudly coloured alien planets. Sorry, not freegans - freegunners. Freeganism is a…",
    url: "https://www.rockpapershotgun.com/overwatchy-fps-concord-gets-new-trailer-and-august-pc-release-date-with-a-beta-in-july",
    urlToImage: "https://assetsio.gnwcdn.com/concord.png?width=1200&height=630&fit=crop&enable=upscale&auto=webp",
    publishedAt: "2024-05-31T09:56:15Z",
    content: "Sony have dropped a trailer and release date for Concord, a new 5V5 multiplayerFPS in which you play a bunch of freegans carrying out heists (divided into six modes) on various loudly coloured alien … [+2784 chars]",
  },
  {
    source: { id: null, name: "WAVY.com" },
    author: "Sarah Goode",
    title: "Learning about Endangered Species at the Virginia Aquarium",
    description: "Tomorrow is Endangered Species Day. Visit the Virginia Aquarium and learn more about species from Komodo Dragons to Sea Turtles, right in Virginia Beach.",
    url: "https://www.wavy.com/news/local-news/learning-about-endangered-species-at-the-virginia-aquarium/",
    urlToImage: "https://media.zenfs.com/en/wavy_articles_285/8fd0c3e24d86a7acaac5c6713df242f1",
    publishedAt: "2024-05-16T15:46:48Z",
    content: "Educator and Community Engagement Coordinator Max Wright talks about Endangered Species Day at the Digital Desk.\r\nVIRGINIA BEACH, Va. (WAVY) Whats an endangered species? Are you aware of ones that li… [+3266 chars]",
  },
  {
    source: { id: null, name: "Thekitchn.com" },
    author: "Ivy Manning",
    title: "The $7 Pantry Staple I Buy at World Market Whenever It’s in Stock (I’ve Already Gone Through 4 Jars!)",
    description: "“I use it right out of the jar on everything.”\nREAD MORE...",
    url: "https://www.thekitchn.com/kuze-fuku-and-sons-garlic-miso-topping-review-23660080",
    urlToImage: "https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_auto,w_1500,ar_3:2/stock%2Fshutterstock_1143176618",
    publishedAt: "2024-05-22T14:30:00Z",
    content: "We independently select these products—if you buy from one of our links, we may earn a commission. All prices were accurate at the time of publishing.\r\nIve been a Japanese food enthusiast for 20 year… [+4549 chars]",
  },
  {
    source: { id: null, name: "Phys.Org" },
    author: "Amy Fallah",
    title: "Collapse in migratory fish populations threatens health of millions and critical freshwater ecosystems",
    description:
      "Populations of migratory freshwater fish species—including salmon, trout, eel, and sturgeon—continue to decline across the globe. This decline risks the food security and livelihoods of millions of people, the survival of countless other species, and the heal…",
    url: "https://phys.org/news/2024-05-collapse-migratory-fish-populations-threatens.html",
    urlToImage: "https://scx2.b-cdn.net/gfx/news/2024/staggering-collapse-in.jpg",
    publishedAt: "2024-05-21T19:50:02Z",
    content:
      "This article has been reviewed according to Science X's \r\neditorial process\r\nand policies.\r\nEditors have highlighted\r\nthe following attributes while ensuring the content's credibility:\r\nfact-checked\r… [+5760 chars]",
  },
  {
    source: { id: null, name: "Phys.Org" },
    author: "Felicia Spencer",
    title: "Researchers confirm scale matters in determining vulnerability of freshwater fish to climate changes",
    description:
      "The silver chub isn't considered sensitive to climate change on a national scale, but context matters. For example, if climate change sensitivity is evaluated in only one region of the United States, the freshwater fish appears quite a bit more susceptible.",
    url: "https://phys.org/news/2024-05-scale-vulnerability-freshwater-fish-climate.html",
    urlToImage: "https://scx2.b-cdn.net/gfx/news/2024/researchers-confirm-sc.jpg",
    publishedAt: "2024-05-17T17:24:03Z",
    content:
      "This article has been reviewed according to Science X's \r\neditorial process\r\nand policies.\r\nEditors have highlighted\r\nthe following attributes while ensuring the content's credibility:\r\nfact-checked\r… [+3984 chars]",
  },
  {
    source: { id: null, name: "Yahoo Entertainment" },
    author: "Daniel Cooper",
    title: "Making bread by hand is hard, are breadmakers better?",
    description:
      "There’s no finer pleasure than starting the day with a slice of hot, fresh bread dripping in salted butter. Poets have waxed on about the joys of transforming so few ingredients into such a beautiful foodstuff for millennia. But unless life has been very good…",
    url: "https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_f5a6cc5a-a1a5-44f8-ae7a-c35e56e056e5",
    urlToImage: null,
    publishedAt: "2024-05-27T12:00:03Z",
    content: "If you click 'Accept all', we and our partners, including 238 who are part of the IAB Transparency &amp; Consent Framework, will also store and/or access information on a device (in other words, use … [+678 chars]",
  },
  {
    source: { id: "new-scientist", name: "New Scientist" },
    author: "James Dinneen",
    title: "Huge jellyfish invasion could disrupt Arctic ecosystems as waters warm",
    description: "The Arctic could see a surge of jellyfish as climate change leads to warmer waters and less ice – a process known as “jellification”",
    url: "https://www.newscientist.com/article/2431126-huge-jellyfish-invasion-could-disrupt-arctic-ecosystems-as-waters-warm/",
    urlToImage: "https://images.newscientist.com/wp-content/uploads/2024/05/14213453/SEI_204090974.jpg",
    publishedAt: "2024-05-15T08:01:01Z",
    content: "A hydrozoan called Aglantha digitale\r\nMario Hoppmann, AWI\r\nAs Arctic waters warm and sea ice melts due to climate change, many species of jellyfish and other zooplankton could expand towards the nort… [+2436 chars]",
  },
];
